### ISSUE TITLE
MemoryError: std::bad_alloc on Fedora 31 from clean install

### ISSUE THREAD

**Issue by m9h** [avramidis/sodecl#10]
**Describe the bug**
Following the example test program instructions as documented on the website
Run currently on a Lenovo X1 Carbon laptop with Intel CPU/GPU

[mhough@fedora-ibm examples]$ python3 kuramoto_euler_stochastic.py 
Traceback (most recent call last):
  File "kuramoto_euler_stochastic.py", line 53, in <module>
    dt, tspan, ksteps, localgroupsize)
  File "/home/mhough/Documents/sodecl/build/examples/sodecl.py", line 77, in sodecl
    localgroupsize)
MemoryError: std::bad_alloc

**To Reproduce**

sudo dnf install redhat-lsb-core
sudo dnf copr enable jdanecki/intel-opencl
sudo dnf install intel-opencl
sudo dnf install ocl-icd ocl-icd-devel

git clone https://github.com/avramidis/sodecl.git
cd sodecl
git submodule update --init

mkdir build
cd build
cmake ..
make
cd examples
python3 kuramoto_euler_stochastic.py

**Expected behavior**
Compute results runtime: 0.0690873 sec.
Simulation execution time:  0.5892870426177979  seconds.

Or similar numbers

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version: 31

**Additional context**
Python 3.7.4

**Comment by avramidis** [comment]
Hello @m9h, could you try again with the master branch?
I think the problem was with one of the Fedora OpenCL platforms. It seems that is broken.

**Comment by m9h** [comment]
Hey @avramidis,

Thanks again for your project and your time. I did notice several OpenCL updates in the last couple days.

I just tried a clean install of Fedora 31 on an Intel NUC Skull Canyon and it worked like a charm. I will update all the code and dependencies on the laptop and see if its fixed there too.

**Comment by m9h** [comment]
Hi again @avramidis,

All good now on the Lenovo laptop that was showing the memory problem originally.

Here's the output from sodecllog.txt:

The platform name is Intel(R) OpenCL HD Graphics
        The platform version is OpenCL 2.1 
        The device name is Intel(R) Gen9 HD Graphics NEO
The platform name is Portable Computing Language
        The platform version is OpenCL 1.2 pocl 1.5-pre, RelWithDebInfo, LLVM 9.0.0, RELOC, SLEEF, DISTRO, POCL_DEBUG
        The device name is pthread-Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
The platform name is Clover
        The platform version is OpenCL 1.1 Mesa 19.2.2
Selected platform name: Intel(R) OpenCL HD Graphics
Selected device name: Intel(R) Gen9 HD Graphics NEO
Selected device OpenCL version: OpenCL 2.1 NEO 
kernels/stochastic_euler.cl
Build options string: -I. 
The local group size is: 0
Compute results runtime: 0.0155985sec.

**Comment by avramidis** [comment]
OK, thanks! That is good. I can see three platforms and two of them are for the integrated GPU. I think I will have to add functionality to choose automatically the CPU or GPU depending on user's requirements.
