### ISSUE TITLE
No module named 'sodecl'

### ISSUE THREAD

**Issue by boohann** [avramidis/sodecl#11]
Hi,

Do you know what this error could mean:

No module named 'sodecl'

I've gone through the installation process on Debian 10 with lsb being installed via alien. Everything seemed to install correctly.

Many thanks,
Niall

**Comment by avramidis** [comment]
Did you try to run one of the python examples? When you build there is sodecl.py and a so library that is needed to run the python example. I will create better install docs.

**Comment by boohann** [comment]
Great, I'll look at that. Many thanks
