### ISSUE TITLE
Implement a better way to wrap SODECL for Python3

### ISSUE THREAD

**Issue by avramidis** [avramidis/sodecl#2]
**Is your feature request related to a problem? Please describe.**
Currently, the user can use SODECL through a Python3 script ([see file](https://github.com/avramidis/sodecl/blob/59aae8becc584a3f5fe0efdd993575fcc3dd89ca/src/pythonscripts/sodecl.py)) that executes a C++ executable ([see C++ code for the main function](https://github.com/avramidis/sodecl/blob/59aae8becc584a3f5fe0efdd993575fcc3dd89ca/src/sodecl.cpp)). The parameters and data needed by SODECL are passed with command line arguments and files. The problem with the current solution is that the overhead of creating/reading the data files needed by SODECL and the command line arguments could be eliminated. Moreover, the writing/reading files and command line arguments is not an elegant way to use C++ libraries with Python3.

**Describe the solution you'd like**
There are a number of options to extend Python3 with C++ functionality ([see here](http://intermediate-and-advanced-software-carpentry.readthedocs.io/en/latest/c++-wrapping.html) and [here](https://docs.python.org/3/extending/building.html)). A solution like this would be better than the current one. This will also allow to create a stand-alone Python3 package that users can download, install and use.

**Describe alternatives you've considered**
I haven't thought of any alternative, however, I am open to discussion.

**Additional context**
None

**Comment by martintoreilly** [comment]
Hi @avramidis. [pybind11](https://pybind11.readthedocs.io/en/stable/) is the library we were talking about today for exposing C++ functions via Python.

**Comment by avramidis** [comment]
Created the branch feature/python3wrapper to work on this issue.

**Comment by avramidis** [comment]
The implementation of the Python3-SODECL interface is done using pybind11. They change are merge to develop and master. Pre-Release  d55c9ba includes the changes.
