### ISSUE TITLE
Failed to build example executable on Fedora 30

### ISSUE THREAD

**Issue by m9h** [avramidis/sodecl#9]
**Describe the bug**
Error: -11 when executing "python3 kuramoto_euler_stochastic.py "

**To Reproduce**
Steps to reproduce the behavior on Fedora 30

git clone https://github.com/avramidis/sodecl.git
cd sodecl
git submodule update --init

sudo dnf install redhat-lsb-core
sudo dnf install dnf-plugins-core
sudo dnf copr enable jdanecki/intel-opencl
sudo dnf install intel-opencl
sudo dnf install ocl-icd ocl-icd-devel

mkdir build
cd build
cmake ..
make
cd examples
python3 kuramoto_euler_stochastic.py

**Output**
[mhough@hades-fedora examples]$ python3 kuramoto_euler_stochastic.py 
Error: -11
Error: Failed to build program executable!
0��J�
Failed to build kernel.
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Attribute Qt::AA_EnableHighDpiScaling must be set before QCoreApplication is created.
Traceback (most recent call last):
  File "kuramoto_euler_stochastic.py", line 55, in <module>
    plt.plot(t, results[0, :])
  File "/usr/lib64/python3.7/site-packages/matplotlib/pyplot.py", line 2811, in plot
    is not None else {}), **kwargs)
  File "/usr/lib64/python3.7/site-packages/matplotlib/__init__.py", line 1798, in inner
    return func(ax, *args, **kwargs)
  File "/usr/lib64/python3.7/site-packages/matplotlib/axes/_axes.py", line 1611, in plot
    for line in self._get_lines(*args, **kwargs):
  File "/usr/lib64/python3.7/site-packages/matplotlib/axes/_base.py", line 393, in _grab_next_args
    yield from self._plot_args(this, kwargs)
  File "/usr/lib64/python3.7/site-packages/matplotlib/axes/_base.py", line 370, in _plot_args
    x, y = self._xy_from_xy(x, y)
  File "/usr/lib64/python3.7/site-packages/matplotlib/axes/_base.py", line 231, in _xy_from_xy
    "have shapes {} and {}".format(x.shape, y.shape))
ValueError: x and y must have same first dimension, but have shapes (26,) and (0,)

**Expected output**
Compute results runtime: 0.0690873 sec.
Simulation execution time:  0.5892870426177979  seconds.

**Desktop (please complete the following information):**
 - OS: Fedora 30
https://getfedora.org/
 - HW: Intel NUC Hades Canyon
https://www.intel.com/content/www/us/en/products/boards-kits/nuc/kits/nuc8i7hvk.html

**Additional context**
clinfo shows additional platforms available
other examples also fail with the same error output

**Comment by avramidis** [comment]
Hello @m9h, 

Thank you for trying the library. This problem could be cause by the different encoding of the OpenCL files in the kernels folder. The line endings should be set to LF. Could you change that and try again? 

I tried to create a VM with Fedora but had problems with the VM. I will try to create a new test build with Fedora and test it.

**Comment by m9h** [comment]
Hi avramidis,

Sorry for the long delay. Previously, I tried your suggestion of changing the kernel line endings to no avail. All I did was run dos2unix across all *.cl files. 

Now, the good news. It's working! I am running the latest version of Fedora (31-beta) but I was getting the same problems initially. I also added running dos2unix on all .hpp files in src as well. I will try and pin down if that really made the difference. 

This is kind of a weird NUC in that it has an Intel GPU and an AMD GPU and I haven't yet installed the comparable AMD OpenCL drivers to provide an OpenCL 2.1 interface for that GPU. Here is my sodecllog.txt:

The platform name is Intel(R) OpenCL HD Graphics
        The platform version is OpenCL 2.1 
        The device name is Intel(R) Gen9 HD Graphics NEO
The platform name is Clover
        The platform version is OpenCL 1.1 Mesa 19.2.0-rc3
        The device name is AMD VEGAM (DRM 3.33.0, 5.3.0-0.rc6.git0.1.fc31.x86_64, LLVM 8.0.0)
The platform name is Portable Computing Language
        The platform version is OpenCL 1.2 pocl 1.3-pre RelWithDebInfo, LLVM 8.0.0, SLEEF, DISTRO, POCL_DEBUG
        The device name is pthread-Intel(R) Core(TM) i7-8809G CPU @ 3.10GHz
Selected platform name: Intel(R) OpenCL HD Graphics
Selected device name: Intel(R) Gen9 HD Graphics NEO
Selected device OpenCL version: OpenCL 2.1 NEO 
kernels/stochastic_euler.cl
Build options string: -I. 
The local group size is: 0
Compute results runtime: 0.018348sec.

**Comment by avramidis** [comment]
Thank you for the update. Maybe the OpenCL runtime was the problem. I will keep this issue open to investigate further later. 
Many thanks!!

**Comment by avramidis** [comment]
Something else about different OpenCL drivers/runtimes. Based on my experience Intel drivers provide the best performance on Intel CPUs by far. So try different drivers for your hardware to make sure that you have the best drivers installed.

**Comment by m9h** [comment]
Just wanted to say that this also no longer seems to be an issue. I just git clone the repo and when I have the dependencies installed everything works.

**Comment by avramidis** [comment]
I will close this issue but there seems to be something funny with fedora and sodecl. I have a CI with fedora and sometimes it fails (see https://gitlab.com/avramidis/sodecl/-/jobs/340286021). I am doing a refactoring of sodecl and I guess I will find out what is the actual cause of these fails.
